= Document Title
v1.0, 2024-07-26
:toc: left
:icons: font
:source-highlighter: rouge
:description: Java Champions' CoC proposal

.About

People from many different backgrounds come together in online communities. The Java Champions are eager to provide a friendly, safe, and welcoming environment for everyone, regardless of gender identity and expression, sexual orientation, disability, neurodiversity, physical appearance, body size, ethnicity, nationality, race, age, religion, or other similar personal characteristics.

The first goal of the Code of Conduct is to establish a basic standard of behavior so that people with different social values and communication styles can participate effectively, productively, and respectfully in the development community.

The second goal is to provide a mechanism for resolving community conflicts when they arise.

The third goal of the Code of Conduct is to make our community welcoming to people from all backgrounds. Diversity is critical to the project; for the Java Champions' community to be successful, it needs contributors and users from all backgrounds; many community members won't feel comfortable participating in a group that is not actively and explicitly committed to a welcoming environment.

We believe that healthy debate and disagreement are essential to a healthy project and community. However, it is never ok to be disrespectful. We value diverse opinions, but we value respectful behavior more.

Values
These are the values to which people in the Java Champions’ Community should aspire.

Be friendly and welcoming
Be patient
Remember that people have varying communication styles and that not everyone is using their native language. (Meaning and tone can be lost in translation.)
Be thoughtful
Productive communication requires effort. Think about how your words will be interpreted.
Remember that sometimes it is best to refrain entirely from commenting.
Be respectful
In particular, respect differences of opinion.
Be charitable
Interpret the arguments of others in good faith, do not seek to disagree.
When we do disagree, try to understand why.
Avoid destructive behavior:
Derailing: stay on topic; if you want to talk about something else, start a new conversation.
Unconstructive criticism: don't merely decry the current state of affairs; offer—or at least solicit—suggestions as to how things may be improved.
Snarking (pithy, unproductive, sniping comments)
Discussing potentially offensive or sensitive issues; this all too often leads to unnecessary conflict.
Microaggressions: brief and commonplace verbal, behavioral and environmental indignities that communicate hostile, derogatory or negative slights and insults to a person or group.
People are complicated. You should expect to be misunderstood and to misunderstand others; when this inevitably occurs, resist the urge to be defensive or assign blame. Try not to take offense where no offense was intended. Give people the benefit of the doubt. Even if the intent was to provoke, do not rise to it. It is the responsibility of all parties to de-escalate conflict when it arises.

== Code of Conduct
=== Our Pledge

In the interest of fostering an open and welcoming environment, we as contributors and maintainers pledge to making participation in our project and our community a harassment-free experience for everyone, regardless of age, body size, disability, ethnicity, gender identity and expression, level of experience, education, socio-economic status, nationality, personal appearance, race, religion, or sexual identity and orientation.

=== Our Standards

Examples of behavior that contributes to creating a positive environment include:

Using welcoming and inclusive language
Being respectful of differing viewpoints and experiences
Gracefully accepting constructive criticism
Focusing on what is best for the community
Showing empathy towards other community members
Examples of unacceptable behavior by participants include:

The use of sexualized language or imagery and unwelcome sexual attention or advances
Trolling, insulting/derogatory comments, and personal or political attacks
Public or private harassment
Publishing others’ private information, such as a physical or electronic address, without explicit permission
Other conduct which could reasonably be considered inappropriate in a professional setting
Scope

This Code of Conduct applies both within project spaces and in public spaces when an individual is representing the Java Champions’ Community.

Examples of representing the community include using an official project e-mail address, posting via an official social media account, or acting as an appointed representative at an online or offline event.

=== Conflict Resolution

We do not believe that all conflict is bad; healthy debate and disagreement often yield positive results. However, it is never okay to be disrespectful or to engage in behavior that violates the project’s code of conduct.

If you see someone violating the code of conduct, you are encouraged to address the behavior directly with those involved. Many issues can be resolved quickly and easily, and this gives people more control over the outcome of their dispute. If you are unable to resolve the matter for any reason, or if the behavior is threatening or harassing, report it. We are dedicated to providing an environment where participants feel welcome and safe.

=== Attribution

This Code of Conduct is adapted from the Contributor Covenant, version 1.4, available athttps://www.contributor-covenant.org/version/1/4/code-of-conduct.html and based on the Code of Conduct of the Golang Project https://golang.org/conduct
